### ISSUE TITLE
service->implementation->IdeaServiceImpl - addIdea() 

### ISSUE THREAD

**Issue by traineratoss2** [traineratoss/AIMSServer2023#5]
for (CategoryDTO categoryDTO : idea.getCategoryList()) { 
            Category category = categoryRepository.findByText(modelMapper.map(categoryDTO, Category.class).getText()); 
            if (category == null) {
 // if it is null the category should be created or throwing an exception to be handled
                savedIdea.getCategoryList().add(modelMapper.map(categoryDTO, Category.class));
            } else { 
                savedIdea.getCategoryList().add(category);
            }
        }
		...
		user.getIdeas().add(savedIdea); - //si functioneaza daca lista e goala initial? 
// does it work if the initial list of ideas for the user is null?

**Comment by rarestrifu** [comment]
The category creation is handled in the if statement. If it is null, a new category is automatically created when adding a new Category mapped, since we added a cascade and it will be present in the DB. The cascade is PERSIST since we dont want to delete a category when deleting an idea (its category). (ManyToMany relationship)

Basically, "savedIdea.getCategoryList().add(modelMapper.map(categoryDTO, Category.class));" this will create me a new category, without having to use the code inside the category implementation.

I understand what you are trying to fix, the example would look like this:

if (category == null) {
                CategoryDTO newCategory = categoryService.addCategory(categoryDTO);
                savedIdea.getCategoryList().add(modelMapper.map(newCategory, Category.class));
            } else {
                savedIdea.getCategoryList().add(category);
            }
}

BUT, after adding a new category using the service, by saving the categoryList, we automatically add a new one. I checked it.
The issue here is that we also need to save the category in the idea's list of categories.

My logic might be wrong, please let me know what you think.

I solved the user issue by checking if it is null or not. If it is, before adding an element, we initialize it as an empty ArrayList.
